version: '3.6'
services:
  ui:
    container_name: ui
    image: gcr.io/coinos-326717/github.com/coinos/coinos-ui:prod
    restart: always
    ports:
      - '3121:3121'
    environment:
      NODE_ENV: production
      ORIGIN: "https://v2.coinos.io"
      PORT: 3121
    extra_hosts:
      - host.docker.internal:host-gateway
networks: 
  default: 
    name: net
    external: true
